[package]
name = "arcana-codegen-impl"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
strum = { version = "0.21", features = ["derive"] }
syn = "1.0"
synthez = "0.1"
