[package]
name = "arcana"
version = "0.1.0"
edition = "2018"

[dependencies]
arcana-core = { version = "0.1.0", path = "./core" }
arcana-codegen = { version = "0.1.0", path = "./codegen" }

[workspace]
members = ["codegen", "codegen/impl", "core"]
