[package]
name = "arcana"
version = "0.1.0-dev"
edition = "2018"
resolver = "2"
description = "Opionated CQRS/ES framework with type magic."
authors = [
    "Ilya Solovyiov <ilya.solovyiov@gmail.com>",
    "Kai Ren <tyranron@gmail.com>",
]
documentation = "https://docs.rs/arcana-core"
homepage = "https://github.com/arcana-rs/arcana"
repository = "https://github.com/arcana-rs/arcana"
readme = "README.md"

[features]
doc = ["arcana-codegen/doc"] # only for generating documentation
derive = ["arcana-codegen", "arcana-core/codegen"]
es = ["arcana-core/es"]

[dependencies]
arcana-core = { version = "0.1.0-dev", path = "./core" }
arcana-codegen = { version = "0.1.0-dev", path = "./codegen", optional = true }

[dev-dependencies]
derive_more = "0.99"
either = "1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
pin-project = "1"
static_assertions = "1"

[[example]]
name = "adapter"
required-features = ["es", "derive"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace]
members = ["codegen", "codegen/impl", "codegen/shim", "core", "examples/chat"]
