[package]
name = "arcana"
version = "0.1.0-dev"
edition = "2018"

[features]
default = ["derive", "es"]
derive = []
es = ["arcana-core/es"]

[dependencies]
arcana-core = { version = "0.1.0-dev", path = "./core" }
arcana-codegen = { version = "0.1.0-dev", path = "./codegen" }

[workspace]
members = ["codegen", "codegen/core", "codegen/shim", "core"]
