[package]
name = "arcana"
version = "0.1.0"
edition = "2018"

[features]
default = ["derive", "es"]
derive = ["es"]
es = ["arcana-core/es"]

[dependencies]
arcana-core = { version = "0.1.0", path = "./core" }
arcana-codegen = { version = "0.1.0", path = "./codegen" }
static_assertions = "1.1"
once_cell = "1.8"

[workspace]
members = ["codegen", "codegen/impl", "core"]
