[package]
name = "arcana"
version = "0.1.0-dev"
edition = "2018"
resolver = "2"
description = "Opionated CQRS/ES framework with type magic."
authors = [
    "Ilya Solovyiov <ilya.solovyiov@gmail.com>",
    "Kai Ren <tyranron@gmail.com>"
]
documentation = "https://docs.rs/arcana-core"
homepage = "https://github.com/arcana-rs/arcana"
repository = "https://github.com/arcana-rs/arcana"
readme = "README.md"

[features]
derive = ["arcana-codegen"]
es = ["arcana-core/es"]

[dependencies]
arcana-core = { version = "0.1.0-dev", path = "./core" }
arcana-codegen = { version = "0.1.0-dev", path = "./codegen", optional = true }

[workspace]
members = ["codegen", "codegen/core", "codegen/shim", "core"]
