[package]
name = "arcana-codegen-shim"
version = "0.1.0-dev"
edition = "2018"
resolver = "2"
description = "Internal proc macro shim of `arcana-codegen` crate."
authors = [
    "Ilya Solovyiov <ilya.solovyiov@gmail.com>",
    "Kai Ren <tyranron@gmail.com>"
]
documentation = "https://docs.rs/arcana-codegen"
homepage = "https://github.com/arcana-rs/arcana/tree/master/codegen"
repository = "https://github.com/arcana-rs/arcana"
readme = "README.md"

[lib]
proc-macro = true

[features]
doc = ["arcana-codegen-core/doc", "arcana-core"] # only for generating documentation

[dependencies]
arcana-codegen-core = { version = "0.1.0-dev", path = "../core" }
syn = { version = "1.0.72", features = ["parsing", "proc-macro"], default-features = false }

# `doc` feature
arcana-core = { version = "0.1.0-dev", path = "../../core", features = ["es"], optional = true }
