[package]
name = "arcana-codegen"
version = "0.1.0"
edition = "2018"

[dependencies]
arcana-codegen-shim = { version = "0.1.0", path = "./shim"}
static_assertions = "1.1"

[dev-dependencies]
arcana-core = { path = "../core" }
