[package]
name = "arcana-codegen"
version = "0.1.0-dev"
edition = "2018"

[dependencies]
arcana-codegen-shim = { version = "0.1.0-dev", path = "./shim"}
arcana-core = { version = "0.1.0-dev", path = "../core" }
static_assertions = "1.1"
