[package]
name = "arcana-core"
version = "0.1.0-dev"
edition = "2018"
resolver = "2"
description = "Core abstractions and implementations of `arcana` crate."
authors = [
    "Ilya Solovyiov <ilya.solovyiov@gmail.com>",
    "Kai Ren <tyranron@gmail.com>",
]
documentation = "https://docs.rs/arcana-core"
homepage = "https://github.com/arcana-rs/arcana/tree/master/core"
repository = "https://github.com/arcana-rs/arcana"
readme = "README.md"

[features]
es = ["derive_more", "futures", "pin-project", "ref-cast", "sealed"]

[dependencies]
derive_more = { version = "0.99", features = ["deref", "deref_mut", "display", "into"], default-features = false, optional = true }
futures = { version = "0.3", default-features = false, optional = true }
pin-project = { version = "1.0", optional = true }
ref-cast = { version = "1.0", optional = true }
sealed = { version = "0.3", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
